image: toliak/latex:minimal

prettier:
    script:
        - npm ci
        - npm run prettier

pdf:
    script:
        - npm install
        - npm run build

    artifacts:
        paths:
            - '*.pdf'
